### PR TITLE
Abbie changes 2

### PR DESCRIPTION
**Pull request by abigailStev**
Most of my paper changes and comments from last week.

### CODE REVIEW

**Comment by abigailStev** [comment]
@dhuppenkothen @matteobachetti Two things for figures (I tried but couldn't run the notebooks since I don't have the data sub-directory): in Fig 1 left panel we should define "MET" (is it mission elapsed time?) and in Fig 4 left panel the units should be "Power [rms^2/mean/Hz]".

**Comment by matteobachetti** [comment]
@abigailStev @dhuppenkothen In Fig. 1, I don't think time is in MET. MET should be seconds from MJDREF, while in the figure it appears to be seconds from the start of the observation.

**Comment by dhuppenkothen** [comment]
I think this is MET, since at the lower right corner there's the "+5.14597e8" that matplotlib is so fond of. Might be more straightforward to plot it in seconds since start of observation, though?

**Comment by dhuppenkothen** [comment]
Please take a look at PR #10 for the new figures? Does that fix those two issues?

**Pull request merged**
